name: CI

on:
  push:
  pull_request:

env:
  GO_VERSION: '1.24.6'
  GORELEASER_VERSION: 'v1.26.2'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Coverage & Snapshot Artifacts
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download modules
        run: go mod download

      - name: Run coverage
        run: make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: /tmp/yaci-coverage/coverage-merged.out
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos

      - name: Clean coverage HTML
        run: rm -f coverage.html

      - name: Goreleaser snapshot (build-only)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: ${{ env.GORELEASER_VERSION }}
          args: release --snapshot --clean

      - name: Collect artifacts
        run: |
          mkdir -p /tmp/artifacts
          shopt -s nullglob
          mv dist/yaci_*.tar.gz dist/yaci_*.txt /tmp/artifacts || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-artifacts
          path: /tmp/artifacts
          if-no-files-found: ignore

  security:
    name: Security (govulncheck)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - run: make govulncheck
